### ISSUE TITLE
Typo in 'Showcase'

### ISSUE THREAD

**Issue by habi** [kort/kort-native#29]
It should probably say 'OpenStreetMap' instead of 'OpenStreetMaps'

![img_3696](https://user-images.githubusercontent.com/1651235/27842600-9da0e2e8-610b-11e7-98f0-951bbfc46e07.PNG)

**Comment by and01** [comment]
Also, "Let's start" instead of "Let''s start"

**Comment by habi** [comment]
> Also, "Let's start" instead of "Let''s start"
> 
Didn't see that one ;)

**Comment by habi** [comment]
I've tried to submit a PR to try and help...
