### ISSUE TITLE
Setting 'opening_hours' does not work reliably

### ISSUE THREAD

**Issue by habi** [kort/kort-native#30]
I've tried to add `opening_hours` to a nearby shop.
The slider does not work reliably, after setting it like in the first screenshot below, I get the hours shown in the second screenshot.
(I selected 09:00, added 09:44)
![img_3701](https://user-images.githubusercontent.com/1651235/27866470-c82c49e0-6196-11e7-93df-626a5cabab2e.PNG)
![img_3702](https://user-images.githubusercontent.com/1651235/27866471-c848f0f4-6196-11e7-883d-74defe212da6.PNG)

**Comment by habi** [comment]
The `opening_hours` editor in the [Maps.me app](https://github.com/mapsme/omim) is really convenient, maybe there's something to borrow from.

**Comment by and01** [comment]
The problem is probably caused by the wheel still spinning. The value is adopted only when the wheel stopped. Also only on clicking "Confirm".
