### ISSUE TITLE
Check how Mission data is sent to client (incl. icon images) so that new Missions can easily be added server-side (affects API)

### ISSUE THREAD

**Issue by sfkeller** [kort/kort-native#38]
See also https://github.com/kort/kort-core/issues/8 .

**Comment by and01** [comment]
All mission information is served by the backend. New missions can easily be added on the backend without updating the client. However, for the sake of device optimized images and loading times, all relevant mission images have been bundled with the mobile app. When `achievementImageURI` points to a remote URL, however, this image is loaded. Check the documentation chapter 9.3. Adding New Mission Types.
