### ISSUE TITLE
Refactor input types to indicate and control user input on clients (affects API)

### ISSUE THREAD

**Issue by sfkeller** [kort/kort-native#39]
See also https://github.com/kort/kort-core/issues/9 .

**Comment by and01** [comment]
inputType.name is an enum.
`name (string, optional): name of the input type = ['number', 'select', 'text']stringEnum:"number", "select", "text",`
see also swagger doc for model description:
https://kort.dev.ifs.hsr.ch/v1.0/ui/#!/Mission/api_missions_get_missions
