### ISSUE TITLE
Quest answer doesn't match phone language

### ISSUE THREAD

**Issue by habi** [kort/kort-native#40]
When solving a 'language' quest, the possible answers don't match the language I set on my phone.
Answers are in German (used to be English), phone language is English (iOS 11 Beta 7, Kort 0.9.1 (1) from TestFlight-App).

![img_4089](https://user-images.githubusercontent.com/1651235/30240431-a091c302-9570-11e7-9bcf-20d9d98e7278.JPG)

**Comment by and01** [comment]
Thanks for hinting at this bug. It has been fixed in the backend. Release will be soon.
