### ISSUE TITLE
Expert mode

### ISSUE THREAD

**Issue by matkoniecz** [kort/kort-native#44]
For me it would be preferable to enable (maybe at cost of losing leaderboard/coins/whatever) expert mode where answers are immediately commited? Like in StreetComplete?

**Comment by sfkeller** [comment]
I understand. But the main target of this app really was not to implement a "domain specific, simplified OSM editor" but really a mini game. That's probably the main difference to StreetComplete.

**Comment by sfkeller** [comment]
Closing for now, since this is considered as beyond the scope of this app. Feel free to make pull requests for such an "expert mode" though.
