### ISSUE TITLE
Add more languages for Language Unknow Missions

### ISSUE THREAD

**Issue by Semigradsky** [kort/kort-native#48]
I haven't found belarusian language.

**Comment by sfkeller** [comment]
Thanks for testing Kort! Missions are configured and driven by the Kort-Core: See e.g. https://github.com/kort/kort-core/blob/v1.0/src/api/res/i18n/KortDB_en.props . The Kort-Native is just the client displaying them. 
Feel free to contribute either in a pull request or in updating the Kort GUI . So closing this issue and moving it over at Transifex: https://www.transifex.com/odi/kort/ .
